devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  user: '!secret mqtt_user'
  password: '!secret mqtt_pass'
  server: mqtt://mosquitto:1883
serial:
  port: >-
    /dev/ttyACM0
  adapter: ember
  baudrate: 115200
  rtscts: false
advanced:
  log_level: warning
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  enabled: true
  port: 8080
  host: 0.0.0.0
version: 4
